### ISSUE TITLE
Does not work with Spring Boot 2

### ISSUE THREAD

**Issue by MrBogue** [nextgearcapital/feign-hystrix-oauth2-spring-boot-starter#10]
Does not work with Spring Boot 2, Are you going to provide a new version?

**Comment by MrBogue** [comment]
Any updates please?

**Comment by scheerer** [comment]
@MrBogue I am longer a member of this organization but I did create a PR with the updated dependencies. @jalmansor will likely need to approve this PR, merge it, and release a solid 2.0.0 version of this artifact.

**Comment by jalmansor** [comment]
@MrBogue our dev tools team is reviewing this and should get back to you soon.

**Comment by MrBogue** [comment]
thanks a lot

**Comment by jasonrberk** [comment]
@MrBogue since #2 was never completed, no one the company has any instructions on how to generate a non-snapshot release.  I did get the snapshot released: 

https://oss.sonatype.org/#nexus-search;quick~feign-hystrix-oauth2-spring-boot-starter

we ask that you please fork this repository as it is slated to be removed in the next 7 days. 

@jalmansor @geekifier
